SenaiCodeReader/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('reader.urls')),
    path('auth/', include('login.urls')),
    path('admin/', admin.site.urls),
]

login/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('cadastro/', views.cadastro, name='cadastro'),
    path('login/', views.login, name='login'),
    path('saiba/', views.saiba, name='saiba'),

    path('', views.send, name='send'),

    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='login/reset/password_reset.html'), name='password_reset'),
    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(template_name='login/reset/password_reset_done.html'), name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='login/reset/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='login/reset/password_reset_complete.html'), name='password_reset_complete'),
]

reader/urls.py
from django.urls import path
from . import views

app_name = "reader"
urlpatterns = [
    path('', views.mecanicas, name='mecanica'),
    path('eletrica/', views.eletricas, name='eletrica'),
    path('eletronica/', views.eletronicas, name='eletronica'),
    path('add/', views.add, name='add'),
    path('save_qr_data/', views.save_qr_data, name='save_qr_data'),
    path('off_to_on/', views.off_to_on, name='off_to_on'),
    path('reset/<str:tabela>/', views.reset, name='reset'),
    path('add_event/', views.add_event, name='add_event'),
    path('remove_event/<int:id>/', views.remove_event, name='remove_event'),
    path('transfer/<str:tabela>/', views.transfer, name='transfer'),
    path('logout/', views.user_logout, name='logout'),
    path('time/', views.time, name='time'),
    path('xlsx/', views.xlsx, name='xlsx'),
    path('upload_file/', views.upload_file, name='upload_file'),
]

reader/models.py
from django.db import models
from django.contrib.auth.models import User

class eventos(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    data = models.DateField()
    evento = models.TextField(max_length=255)

    def save(self, *args, **kwargs):
        if not eventos.objects.filter(id=self.id).exclude(pk=self.pk).exists():
            super(eventos, self).save(*args, **kwargs)

class mecanica(models.Model):
    numero = models.TextField(max_length=255)
    nome = models.TextField(max_length=255)
    local = models.TextField(max_length=255)
    instrutor = models.TextField(max_length=255)
    status = models.TextField(max_length=255)

    def save(self, *args, **kwargs):
        if not mecanica.objects.filter(numero=self.numero).exclude(pk=self.pk).exists():
            super(mecanica, self).save(*args, **kwargs)

class eletrica(models.Model):
    numero = models.TextField(max_length=255)
    nome = models.TextField(max_length=255)
    local = models.TextField(max_length=255)
    instrutor = models.TextField(max_length=255)
    status = models.TextField(max_length=255)

    def save(self, *args, **kwargs):
        if not eletrica.objects.filter(numero=self.numero).exclude(pk=self.pk).exists():
            super(eletrica, self).save(*args, **kwargs)

class eletronica(models.Model):
    numero = models.TextField(max_length=255)
    nome = models.TextField(max_length=255)
    local = models.TextField(max_length=255)
    instrutor = models.TextField(max_length=255)
    status = models.TextField(max_length=255)

    def save(self, *args, **kwargs):
        if not eletronica.objects.filter(numero=self.numero).exclude(pk=self.pk).exists():
            super(eletronica, self).save(*args, **kwargs)

reader/views.py
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_exempt
from .models import mecanica, eletrica, eletronica, eventos
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth import logout
import pandas as pd
import datetime

data = datetime.datetime.now()
data = data - datetime.timedelta(days=1)
data = data.date()

@login_required(login_url='login')
def time(request):
    return render(request, 'reader/times.html')

@login_required(login_url='login')
def mecanicas(request):
    user = request.user
    role = user.is_staff
    return render(request, 'reader/index.html', {'ferramentas': mecanica.objects.all().values(), 'tabela' : 'mecanica', 'evento': eventos.objects.filter(user=request.user).values(), 'user' : user, 'role' : role, 'it' : '', 'data' : data})

@login_required(login_url='login')
def eletricas(request):
    user = request.user
    role = user.is_staff
    return render(request, 'reader/index.html', {'ferramentas': eletrica.objects.all().values(), 'tabela' : 'eletrica', 'evento': eventos.objects.filter(user=request.user).values(), 'user' : user, 'role' : role, 'it' : '', 'data' : data})

@login_required(login_url='login')
def eletronicas(request):
    user = request.user
    role = user.is_staff
    return render(request, 'reader/index.html', {'ferramentas': eletronica.objects.all().values(), 'tabela' : 'eletronica', 'evento': eventos.objects.filter(user=request.user).values(), 'user' : user, 'role' : role, 'it' : '', 'data' : data})

@user_passes_test(lambda u: u.is_staff)
@login_required(login_url='login')
def add(request):
    return render(request, 'reader/add.html')

@login_required(login_url='login')
@csrf_exempt
def save_qr_data(request):
    if request.method == "POST":
        tabela = request.POST.get("tabela")
        if tabela == "mecanica":
            ferramenta = mecanica()
        elif tabela == "eletrica":
            ferramenta = eletrica()
        else:
            ferramenta = eletronica()

        ferramenta.numero = request.POST.get("numero")
        ferramenta.nome = request.POST.get("nome")
        ferramenta.local = request.POST.get("local")
        ferramenta.instrutor = request.POST.get("instrutor")
        ferramenta.status = "off"
        ferramenta.save()
        return redirect('reader:add')

@login_required(login_url='login')
@csrf_exempt
def off_to_on(request):
    if request.method == "POST":
        decodetext = request.POST.get("decodetext")
        tabela = request.POST.get('tabela')
        user = request.user
        role = user.is_staff

        if mecanica.objects.filter(numero=decodetext).exists():
            tabela_encontrada = "mecanica"
            if tabela == tabela_encontrada:
                mecanica.objects.filter(numero=decodetext).update(status="on")
                return redirect('reader:mecanica')
        elif eletrica.objects.filter(numero=decodetext).exists():
            tabela_encontrada = "eletrica"
            if tabela == tabela_encontrada:
                eletrica.objects.filter(numero=decodetext).update(status="on")
                return redirect('reader:eletrica')
        elif eletronica.objects.filter(numero=decodetext).exists():
            tabela_encontrada = "eletronica"
            if tabela == tabela_encontrada:
                eletronica.objects.filter(numero=decodetext).update(status="on")
                return redirect('reader:eletronica')
        else:
            tabela_encontrada = "not"
            return redirect('reader:mecanica')

        if decodetext:
            if tabela == "mecanica":
                return render(request, 'reader/index.html', {'ferramentas': mecanica.objects.all().values(), 'tabela' : 'mecanica', 'evento': eventos.objects.filter(user=request.user).values(), 'user' : user, 'role' : role, 'it' : tabela_encontrada, 'data' : data})
            elif tabela == "eletrica":
                return render(request, 'reader/index.html', {'ferramentas': eletrica.objects.all().values(), 'tabela' : 'eletrica', 'evento': eventos.objects.filter(user=request.user).values(), 'user' : user, 'role' : role, 'it' : tabela_encontrada, 'data' : data})
            else:
                return render(request, 'reader/index.html', {'ferramentas': eletronica.objects.all().values(), 'tabela' : 'eletronica', 'evento': eventos.objects.filter(user=request.user).values(), 'user' : user, 'role' : role, 'it' : tabela_encontrada, 'data' : data})

@login_required(login_url='login')
def reset(request, tabela):
    if tabela == "mecanica":
        mecanica.objects.filter(status="on").update(status="off")
        return redirect('reader:mecanica')
    elif tabela == "eletrica":
        eletrica.objects.filter(status="on").update(status="off")
        return redirect('reader:eletrica')
    else:
        eletronica.objects.filter(status="on").update(status="off")
        return redirect('reader:eletronica')

        
@login_required(login_url='login')
@csrf_exempt
def add_event(request):
    if request.method == 'POST':
        data = request.POST.get('data')
        evento = request.POST.get('evento')
        eventos.objects.create(data=data, evento=evento, user=request.user)
        return redirect('reader:mecanica')

@login_required(login_url='login')
@csrf_exempt
def remove_event(request, id):
    eventos.objects.filter(id=id).delete()
    return redirect('reader:mecanica')

def user_logout(request):
    logout(request)
    return redirect('login')

@login_required(login_url='login')
@csrf_exempt
def transfer(request, tabela):
    if request.method == 'POST':
        tabela_origem = request.POST.get('tabela')
        number = request.POST.get('number')

        tabelas = {
            "mecanica": mecanica,
            "eletrica": eletrica,
            "eletronica": eletronica
        }


        modelo_origem = tabelas[tabela]
        modelo_destino = tabelas[tabela_origem]

        objeto = modelo_origem.objects.get(numero=number)
        
        modelo_destino.objects.create(**{
            field.name: getattr(objeto, field.name)
            for field in modelo_origem._meta.fields
            if field.name != 'id'
        })
        
        objeto.delete()

        return redirect(f'reader:{tabela}')

@user_passes_test(lambda u: u.is_staff)
@login_required(login_url='login')
def xlsx(request):
    return render(request, 'reader/xlsx.html', {'ferramentas': mecanica.objects.all().values(), 'tabela' : 'mecanica'})

def upload_file(request):
    if request.method == 'POST':
        table = request.POST.get('table')
        file = request.FILES.get('file')
        df = pd.read_excel(file)
        model = {
            'mecanica': mecanica,
            'eletrica': eletrica,
            'eletronica': eletronica
        }.get(table)
        for _, row in df.iterrows():
            model.objects.update_or_create(
                numero=row[0],
                defaults={
                    'nome': row[1],
                    'local': row[2],
                    'instrutor': row[3],
                    'status': "off"
                }
            )
        return redirect(f'reader:{table}')

reader/templates/reader/index.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-BR">

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="style.css">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0"/>
    <link rel="stylesheet" href="{% static 'scan/style.css' %}">
    <link rel="shortcut icon" href="{% static 'scan/favicon.ico' %}" type="image/x-icon">
	<title>Integre</title>
</head>
<style>
	@import url('https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap');
</style>

<body style="position: relative;">
    <div id="qrcodez">
        <div id="reader"></div>
    </div>
    <div id="transferDiv" style="display: none;">
        <form action="{% url 'reader:transfer' tabela %}" method="POST">
            <select name="tabela" id="tabela" required>
                <option value="mecanica">Mecanica</option>
                <option value="eletrica">Eletrica</option>
                <option value="eletronica">Eletronica</option>
            </select>
            <input type="text" name="number" id="numberTransfer" style="display: none;">
            <input type="submit" value="submit">
        </form>
    </div>
	<div class="container">
		<!-- barra lateral -->
		<aside class="sidebar" id="nav">
			<div class="logo"><a href="{% url 'reader:mecanica' %}"><img src="{% static 'scan/icon.png' %}"></a></div>
			<nav>
				<div class="part1" id="part1">
					<ul>
                        {% if role == True %}
						<li class="navegacao"> <a style=color:white href="{% url 'reader:add' %}"> &ensp; <span
								class="material-symbols-outlined">add</span> &ensp; Adicionar Item </a></li>
                        {% endif %}
						<li class="navegacao"> <a style=color:white href="{% url 'reader:mecanica' %}"> &ensp; <span
								class="material-symbols-outlined">manufacturing</span> &ensp; Mecânica </a></li>
						<li class="navegacao"> <a style=color:white href="{% url 'reader:eletrica' %}"> &ensp; <span
								class="material-symbols-outlined">bolt</span> &ensp; Elétrica </a></li>
						<li class="navegacao"> <a style=color:white href="{% url 'reader:eletronica' %}"> &ensp; <span
								class="material-symbols-outlined">memory</span> &ensp; Eletrônica </a> </li>
				</div>
				</ul>
				
				<div class="part2" id="part2">
					<ul>
                        {% if role == True %}
						<li class="navegacao" style="margin-top: -7vh;"> <a style=color:white href="{% url 'admin:index' %}"> &ensp; <span
								class="material-symbols-outlined">admin_panel_settings</span> &ensp; Admin </a></li>
                        {% endif %}
                        <li class="navegacao"> <a style=color:white href="{% url 'reader:time' %}"> &ensp; <span
                            class="material-symbols-outlined">group</span> &ensp; Time </a></li>
						<li class="navegacao"> <a style="color:white" href="{% url 'reader:reset' tabela %}" onclick="downloadPDF(event, this)"> &ensp; <span
								class="material-symbols-outlined">restart_alt</span> &ensp; Resetar </a></li>
						<li class="navegacao"> <a style=color:white href="{% url 'reader:logout' %}"> &ensp; <span
								class="material-symbols-outlined">logout</span> &ensp; Sair </a></li>
				</div>
				</ul>
			</nav>
		</aside>
		
		<!-- Meio, Parte principal -->
		<main class="main-content">

			<header>
				<span class="material-symbols-outlined" id="abrir">
					menu
				</span>
				<span class="material-symbols-outlined" id="fecharrr">
					close
				</span>
				<!-- barra de pesquisa -->
				<span>
                    <form action="{% url 'reader:off_to_on' %}" method="POST">
                        <input onclick="openqr()" type="button" class="botaodoluis" value="QRCODE">
                        <input type="text" name="decodetext" id="decodetext" class="pesquisa" placeholder="Pesquisar...">
                        <input type="text" name="tabela" id="tabela" value="{{ tabela }}" style="display: none;">
                        <input type="submit" class="botaodovega" value="BUSCAR">
                    </form>
				</span>
			</header>
			
			<!-- tabela -->
			<section class="tabelapatrimonio">
                <table id="cod" style="margin: 20px auto">
                    <caption style="text-align: center; text-transform: capitalize;">{{tabela}}</caption>
                    <tr>
                        <th>Numero</th>
                        <th>Nome</th>
                        <th>Lugar</th>
                        <th>Instrutor</th>
                        <th>Status</th>
                        <th style="display: flex; justify-content: center;" id="transfer"><span class="material-symbols-outlined" id="transf">move_up</span></th>
                    </tr>
                    {% for ferramenta in ferramentas %}
                    <tr data-id="{{ ferramenta.numero }}" style="position: relative;">
                        <td>{{ferramenta.numero}}</td>
                        <td>{{ferramenta.nome}}</td>
                        <td>{{ferramenta.local}}</td>
                        <td>{{ferramenta.instrutor}}</td>
                        <td {% if ferramenta.status == 'on' %} class="on" {% else %} class="off" {% endif %} >{{ferramenta.status}}</td>
                        <td id="transfer">
                            <a onclick="transfer('{{ferramenta.numero}}')" style="display: flex; justify-content: center; cursor: pointer;">
                                <span class="material-symbols-outlined" id="transf">move_up</span>
                            </a>
                        </td>
                    </tr>
                    {% endfor %}
                </table>
                
				<footer>
                    <button onclick="downloadPDF()">
                        Baixar PDF<span class="material-symbols-outlined">download</span>
                    </button>
                    <button onclick="downloadExcel()">
                        Baixar XLSX<span class="material-symbols-outlined">download</span>
                    </button>
				</footer>
			</section>
		</main>
		
		<!-- area de login, direita  -->
		<aside class="aside2">
			<div class="usuario">
				<div class="circ">
                    <img src="{% static 'scan/person.png' %}">
				</div>
				<div class="user-info">
					<span class="text">{{user}}</span><br>
					<span class="text">
                        {% if role == False %} Membro {% else %} Admin {% endif %}
                    </span>
				</div>
			</div>
			
			<!-- Parte do calendario -->
			<div class="calendario">
				<div id="evento">
					<h2>Adicionar Evento</h2>
                    <form action="{% url 'reader:add_event' %}" method="post">
                        <input type="date" name="data" id="data" required><br>
                        <input type="text" name="evento" id="nomeevento" placeholder="Adicionar evento..." required maxlength="22"><br>
                        <button type="submit" id="adicionar" required style="margin: 5px auto;">Adicionar Evento</button><br>
                    </form>
                    {% for e in evento %}
                    {% if data < e.data %}
                    <a id="eventop" href="{% url 'reader:remove_event' e.id %}">{{ e.data }} : {{ e.evento }}</a>
                    {% else %}
                    <script>
                        location.replace("{% url 'reader:remove_event' e.id %}")
                    </script>
                    {% endif %}
                    {% endfor %}
				</div>
			</div>
		</aside>
	</div>
	
    <script>
        role = "{{role}}"
        function transfer(Item){
            if (role){
                if(document.getElementById('transferDiv').style.display == "none"){
                    document.getElementById('numberTransfer').value = Item
                    document.getElementById('transferDiv').style.display = "flex"
                } else{
                    document.getElementById('transferDiv').style.display = "none"
                }
            }
        }
    </script>

    <script>
        let num_eventos = document.querySelectorAll('#eventop').length
        if (num_eventos >= 5){
            document.getElementById("adicionar").disabled = true;
            document.getElementById("evento").innerHTML += "<p style='color: red; font-weight: bold;' id='aviso'>Máximo de 5 eventos atingido</p>"
        } else{
            document.getElementById("adicionar").disabled = false;
        }
    </script>

	<script src="{% static 'scan/teste1.js' %}"></script>

    <script src="https://unpkg.com/html5-qrcode"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.4.0/jspdf.umd.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.9.2/html2pdf.bundle.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.18.5/xlsx.full.min.js"></script>

    <script>
        document.addEventListener("DOMContentLoaded", (event) => {
            var it = "{{ it }}";
            if (it != ''){
                if (it == 'not'){
                    alert("Item não encontrado")
                } else{
                    alert("Tabela certa do item é {{ it }}")
                }
            }
        });
      </script>

    <script>
        document.getElementById("reader").style.display = "none"
        function openqr(){
            reader = document.getElementById("reader")
            if (reader.style.display == "none"){
                reader.style.display = "block"
            } else{
                reader.style.display = "none"
            }
        }

        function downloadPDF(event, link) {
            event.preventDefault();

            const element = document.getElementById("cod");
            const tabela = "{{tabela}}";
            const dataAtual = new Date();
            const dia = dataAtual.getDate().toString().padStart(2, '0');
            const mes = (dataAtual.getMonth() + 1).toString().padStart(2, '0');
            const ano = dataAtual.getFullYear();
            const dataFormatada = `${dia}-${mes}-${ano}`;

            html2pdf()
                .set({
                    margin: 1,
                    filename: `${tabela} ${dataFormatada}.pdf`,
                    image: { type: 'jpeg', quality: 1.00 },
                    html2canvas: { scale: 2 },
                    jsPDF: { unit: 'in', format: 'a4', orientation: 'portrait' }
                })
                .from(element)
                .save()
                .then(() => {
                    window.location.href = link.href;
                })
        }


        function downloadExcel() {
            const table = document.getElementById("cod");
            const wb = XLSX.utils.book_new(); // Cria um novo workbook
            const ws = XLSX.utils.table_to_sheet(table); // Converte a tabela HTML em uma worksheet
            
            XLSX.utils.book_append_sheet(wb, ws, "Tabela"); // Adiciona a worksheet ao workbook
            
            XLSX.writeFile(wb, "tabela.xlsx"); // Faz o download do arquivo
        }

    </script>

    <script>
        function domready(fn) {
            if (document.readyState === "complete" || document.readyState === "interactive") {
                setTimeout(fn, 1);
            } else {
                document.addEventListener("DOMContentLoaded", fn);
            }
        }
    
        domready(function () {
            var lastresult = 0;
    
            function onScanSuccess(decodetext, decodeesult) {
                lastresult = decodetext;
                fetch('/off_to_on/', {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/x-www-form-urlencoded',
                        'X-CSRFToken': getCookie('csrftoken')
                    },
                    body: `decodetext=${encodeURIComponent(decodetext)}&tabela=${encodeURIComponent("{{ tabela }}")}`
                })
                window.location.reload();
            }

            function getCookie(name) {
                let cookieValue = null;
                if (document.cookie && document.cookie !== '') {
                    const cookies = document.cookie.split(';');
                    for (let i = 0; i < cookies.length; i++) {
                        const cookie = cookies[i].trim();
                        if (cookie.substring(0, name.length + 1) === (name + '=')) {
                            cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                            break;
                        }
                    }
                }
                return cookieValue;
            }
    
            var htmlscanner = new Html5QrcodeScanner(
                'reader', { fps: 10, qrbox: 250 }
            );
    
            htmlscanner.render(onScanSuccess);
        });
    </script>   
</body>
</html>

reader/templates/reader/xlsx.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-BR">

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="style.css">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0"/>
    <link rel="stylesheet" href="{% static 'scan/style.css' %}">
    <link rel="shortcut icon" href="{% static 'scan/favicon.ico' %}" type="image/x-icon">
	<title>Integre</title>
</head>
<style>
	@import url('https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap');
</style>

<body style="position: relative;">
    <div id="qrcodez">
        <div id="reader"></div>
    </div>
	<div class="container">
		<!-- barra lateral -->
		<aside class="sidebar" id="nav">
			<div class="logo"><a href="{% url 'reader:mecanica' %}"><img src="{% static 'scan/icon.png' %}"></a></div>
			<nav>
				<div class="part1" id="part1">
					<ul>
                        {% if role == True %}
						<li class="navegacao"> <a style=color:white href="{% url 'reader:add' %}"> &ensp; <span
								class="material-symbols-outlined">add</span> &ensp; Adicionar Item </a></li>
                        {% endif %}
						<li class="navegacao"> <a style=color:white href="{% url 'reader:mecanica' %}"> &ensp; <span
								class="material-symbols-outlined">manufacturing</span> &ensp; Mecânica </a></li>
						<li class="navegacao"> <a style=color:white href="{% url 'reader:eletrica' %}"> &ensp; <span
								class="material-symbols-outlined">bolt</span> &ensp; Elétrica </a></li>
						<li class="navegacao"> <a style=color:white href="{% url 'reader:eletronica' %}"> &ensp; <span
								class="material-symbols-outlined">memory</span> &ensp; Eletrônica </a> </li>
				</div>
				</ul>
				
				<div class="part2" id="part2">
					<ul>
                        {% if role == True %}
						<li class="navegacao" style="margin-top: -7vh;"> <a style=color:white href="{% url 'admin:index' %}"> &ensp; <span
								class="material-symbols-outlined">admin_panel_settings</span> &ensp; Admin </a></li>
                        {% endif %}
                        <li class="navegacao"> <a style=color:white href="{% url 'reader:time' %}"> &ensp; <span
                            class="material-symbols-outlined">group</span> &ensp; Time </a></li>
						<li class="navegacao"> <a style=color:white href="{% url 'reader:reset' tabela %}"> &ensp; <span
								class="material-symbols-outlined">restart_alt</span> &ensp; Resetar </a></li>
						<li class="navegacao"> <a style=color:white href="{% url 'reader:logout' %}"> &ensp; <span
								class="material-symbols-outlined">logout</span> &ensp; Sair </a></li>
				</div>
				</ul>
			</nav>
		</aside>
		
		<main class="main-content" style="display: flex; justify-content: center; align-items: center;">
			<div style="background-color: #002549; width: 30vw; height: 80vh; display: flex; align-items: center; border: 5px solid #00458a; border-radius: 20px;">
				<form action="{% url 'reader:upload_file' %}" method="post" enctype="multipart/form-data" style="display: flex; justify-content: center; align-items: center; flex-direction: column; width: 100%;">
					{% csrf_token %}
					<label for="table">Escolha a tabela:</label>
					<select name="table" id="table" required>
						<option value="mecanica">Mecânica</option>
						<option value="eletrica">Elétrica</option>
						<option value="eletronica">Eletrônica</option>
					</select><br><br>
					<label for="file">Selecione o arquivo Excel:</label>
					<input type="file" name="file" id="file" accept=".xlsx" required><br><br>
					<button type="submit">Enviar</button>
				</form>
			</div>
		</main>
	</div>  
</body>
</html>